enum Category { CAT, DOG, BUNNY, HAMSTER }

enum Condition { Adoption, Lost, Mating }

class Pet {
  String name;
  String location;
  String distance;
  String condition;
  Category category;
  String imageUrl;
  bool favorite;
  bool popular;
  String age;
  String color;
  String weight;
  String Story;
  bool isAdopted;

  Pet(
      this.name,
      this.location,
      this.distance,
      this.condition,
      this.category,
      this.imageUrl,
      this.favorite,
      this.popular,
      this.age,
      this.color,
      this.weight,
      this.Story,
      {this.isAdopted=false});
}

List<Pet> getPetList() {
  return <Pet>[
    Pet(
        "Abyssinian Cats",
        "California",
        "2.5",
        "Adoption",
        Category.CAT,
        "assets/images/cat_1.jpg",
        true,
        true,
        "4 months",
        "Grey",
        "11 Kg",
        "The Abyssinian is a breed of domestic short-haired cat with a distinctive ticked tabby coat, in which individual hairs are banded with different colors. They are also known simply as Abys. The first members of the breed to be exhibited in England were brought there from Abyssinia, whence the name. "),
    Pet(
        "Scottish Fold",
        "New Jersey",
        "1.2",
        "Mating",
        Category.CAT,
        "assets/images/cat_2.jpg",
        false,
        false,
        "6 months",
        "Grey",
        "9.5 Kg",
        "The Scottish Fold is a distinctive breed of domestic cat characterized by a natural dominant gene mutation associated with osteochondrodysplasia. This genetic anomaly impacts cartilage throughout the body, causing the ears to fold, bending forward and down towards the front of the head. "),
    Pet(
        "Ragdoll",
        "Miami",
        "1.2",
        "Lost",
        Category.CAT,
        "assets/images/cat_3.jpg",
        false,
        false,
        "10 months",
        "Grey",
        "10 Kg",
        "The Ragdoll is a breed of cat with a distinct colorpoint coat and blue eyes. Its morphology is large and weighty, and it has a semi-long and silky soft coat. American breeder Ann Baker developed Ragdolls in the 1960s. They are best known for their docile, placid temperament and affectionate nature."),
    Pet(
        "Burmese",
        "Chicago",
        "1.2",
        "Lost",
        Category.CAT,
        "assets/images/cat_4.jpg",
        true,
        true,
        "4 months",
        "Grey",
        "11 Kg",
        "The Burmese cat is a breed of domestic cat, originating in Southeast Asia and developed in the United States and Britain. Most modern Burmese are descendants of one female cat called Wong Mau, which was brought from Burma to America in 1930. "),
    Pet(
        "American Shorthair",
        "Washington",
        "1.2",
        "Mating",
        Category.CAT,
        "assets/images/cat_5.jpg",
        true,
        false,
        "8 months",
        "Orange",
        "9.5 Kg",
        "The American Shorthair is a breed of domestic cat believed to be descended from European cats brought to North America by early settlers to protect valuable cargo from mice and rats. "),
    Pet(
        "British Shorthair",
        "New York",
        "1.9",
        "Adoption",
        Category.CAT,
        "assets/images/cat_6.jpg",
        false,
        false,
        "4 months",
        "Orange",
        "11 Kg",
        "The British Shorthair is the pedigreed version of the traditional British domestic cat, with a distinctively chunky body, dense coat, and broad face. The most familiar color variant is the \"British Blue,\" a solid grey-blue coat, orange eyes, and a medium-sized tail."),
    Pet(
        "Abyssinian Cats",
        "California",
        "2.5",
        "Adoption",
        Category.CAT,
        "assets/images/cat_7.jpg",
        true,
        false,
        "6 months",
        "Black",
        "10 Kg",
        "The Abyssinian is a breed of domestic short-haired cat with a distinctive ticked tabby coat, in which individual hairs are banded with different colors. They are also known simply as Abys. The first members of the breed to be exhibited in England were brought there from Abyssinia, whence the name. "),
    Pet(
        "Scottish Fold",
        "New Jersey",
        "1.2",
        "Mating",
        Category.CAT,
        "assets/images/cat_8.jpg",
        false,
        false,
        "4 months",
        "White",
        "11 Kg",
        "The Scottish Fold is a distinctive breed of domestic cat characterized by a natural dominant gene mutation associated with osteochondrodysplasia. This genetic anomaly impacts cartilage throughout the body, causing the ears to fold, bending forward and down towards the front of the head. "),
    Pet(
        "Ragdoll",
        "Miami",
        "1.2",
        "Lost",
        Category.CAT,
        "assets/images/cat_9.jpg",
        false,
        true,
        "4 months",
        "Black",
        "11 Kg",
        "The Ragdoll is a breed of cat with a distinct colorpoint coat and blue eyes. Its morphology is large and weighty, and it has a semi-long and silky soft coat. American breeder Ann Baker developed Ragdolls in the 1960s. They are best known for their docile, placid temperament and affectionate nature."),
   
   
    Pet(
        "Roborowski",
        "California",
        "2.5",
        "Adoption",
        Category.HAMSTER,
        "assets/images/hamster_1.jpg",
        true,
        true,
        "4 months",
        "Grey",
        "0.2 Kg",
        "The Roborovski hamster is the smallest of the dwarf hamster varieties. They are known for their small size, typically measuring between 4 and 5 centimeters in length. They are native to the deserts of Central Asia, where they live in burrows and feed on seeds, fruits, and insects."),
    Pet(
        "Ruso",
        "New Jersey",
        "2.5",
        "Mating",
        Category.HAMSTER,
        "assets/images/hamster_2.jpg",
        false,
        false,
        "3 months",
        "Orange",
        "0.2 Kg",
        "The Ruso hamster, also known as the Russian dwarf hamster, is a small species of hamster native to the steppes of central and eastern Europe and Asia. They are a popular pet due to their small size, adorable appearance, and low maintenance requirements."),
    Pet(
        "Golden",
        "Miami",
        "2.5",
        "Lost",
        Category.HAMSTER,
        "assets/images/hamster_3.jpg",
        false,
        false,
        "5 months",
        "Black",
        "0.2 Kg",
        "The Golden hamster, also known as the Syrian hamster, is one of the most popular and widely kept pets in the world. They are known for their friendly disposition, playful behavior, and relatively low maintenance requirements."),
    Pet(
        "Chinese",
        "Chicago",
        "2.5",
        "Lost",
        Category.HAMSTER,
        "assets/images/hamster_4.jpg",
        true,
        true,
        "6 months",
        "Orange",
        "0.2 Kg",
        "The Chinese hamster is a small species of hamster native to northern China and Mongolia. They are known for their long, slender bodies, large ears, and long tails. They are often kept as pets due to their curious and active nature."),
    Pet(
        "Dwarf Campbell",
        "New York",
        "2.5",
        "Adoption",
        Category.HAMSTER,
        "assets/images/hamster_5.jpg",
        true,
        false,
        "6 months",
        "Brown",
        "0.2 Kg",
        "The Dwarf Campbell hamster is a small species of hamster native to central Asia. They are known for their friendly disposition, energetic behavior, and relatively low maintenance requirements. They are popular pets for children and adults alike."),
    Pet(
        "Syrian",
        "California",
        "2.5",
        "Adoption",
        Category.HAMSTER,
        "assets/images/hamster_6.jpg",
        false,
        false,
        "6 months",
        "White",
        "0.2 Kg",
        "The Syrian hamster, also known as the Golden hamster, is one of the most popular and widely kept pets in the world. They are known for their friendly disposition, playful behavior, and relatively low maintenance requirements."),
    Pet(
        "Dwarf Winter",
        "Miami",
        "2.5",
        "Mating",
        Category.HAMSTER,
        "assets/images/hamster_7.jpg",
        true,
        false,
        "7 months",
        "Brown",
        "0.2 Kg",
        "The Dwarf Winter White hamster, also known as the Djungarian hamster, is a small species of hamster native to Siberia and central Asia. They are known for their white fur, which turns grayish-brown in the winter months to provide camouflage in the snow."),
    
    
    Pet(
  "American Rabbit",
  "California",
  "2.5",
  "Adoption",
  Category.BUNNY,
  "assets/images/bunny_1.jpg",
  true,
  true,
  "4 months",
  "White",
  "5 Kg",
  "The American Rabbit is a breed of domestic rabbit that was developed in the United States from rabbits imported from Europe. The American Rabbit is primarily bred as a meat rabbit, but it is also bred for its fur and as a pet."
),
Pet(
  "Belgian Hare Rabbit",
  "New Jersey",
  "2.5",
  "Mating",
  Category.BUNNY,
  "assets/images/bunny_2.jpg",
  false,
  false,
  "5 months",
  "Orange",
  "4.5 Kg",
  "The Belgian Hare is a breed of domestic rabbit that was originally bred for meat, fur, and as a fancy breed. The breed is known for its sleek, athletic build, resembling that of a hare."
),
Pet(
  "Blanc de Hotot Rabbit",
  "Miami",
  "2.5",
  "Lost",
  Category.BUNNY,
  "assets/images/bunny_3.jpg",
  false,
  false,
  "4 months",
  "White",
  "5 Kg",
  "The Blanc de Hotot is a breed of domestic rabbit known for its distinctive appearance, with a white coat and dark, ringed eyes. They are popular as show rabbits and as pets due to their calm and friendly temperament."
),
Pet(
  "Californian Rabbits",
  "Chicago",
  "2.5",
  "Lost",
  Category.BUNNY,
  "assets/images/bunny_4.jpg",
  true,
  true,
  "6 months",
  "White",
  "5 Kg",
  "The Californian Rabbit is a breed of domestic rabbit known for its distinctive markings, with a white body and colored points on the nose, ears, feet, and tail. They are popular as show rabbits and as pets due to their gentle and friendly nature."
),
Pet(
  "Checkered Giant Rabbit",
  "New York",
  "2.5",
  "Adoption",
  Category.BUNNY,
  "assets/images/bunny_5.jpg",
  true,
  false,
  "4 months",
  "White",
  "4.5 Kg",
  "The Checkered Giant is a breed of domestic rabbit known for its large size and distinctive black and white markings. They are popular as show rabbits and as pets due to their calm and gentle temperament."
),
Pet(
  "Dutch Rabbit",
  "California",
  "2.5",
  "Adoption",
  Category.BUNNY,
  "assets/images/bunny_6.jpg",
  false,
  false,
  "4 months",
  "Brown",
  "5 Kg",
  "The Dutch Rabbit is a breed of domestic rabbit known for its distinctive color pattern, with a solid-colored body and a white blaze on the face and a white stripe running down the center of the body. They are popular as pets and for show due to their friendly and outgoing nature."
),
Pet(
  "English Lop",
  "Miami",
  "2.5",
  "Mating",
  Category.BUNNY,
  "assets/images/bunny_7.jpg",
  true,
  false,
  "4 months",
  "White",
  "5 Kg",
  "The English Lop is a breed of domestic rabbit known for its long, floppy ears and gentle disposition. They are popular as pets and for show due to their calm and friendly nature."
),
Pet(
  "English Spot",
  "California",
  "2.5",
  "Adoption",
  Category.BUNNY,
  "assets/images/bunny_8.jpg",
  true,
  true,
  "4 months",
  "White",
  "5 Kg",
  "The English Spot is a breed of domestic rabbit known for its distinctive color pattern, with colored spots on a white background. They are popular as pets and for show due to their energetic and playful nature."
),
   
   
   Pet(
  "Affenpinscher",
  "California",
  "2.5",
  "Adoption",
  Category.DOG,
  "assets/images/dog_1.jpg",
  true,
  true,
  "4 months",
  "White",
  "11 Kg",
  "The Affenpinscher is a small breed of dog characterized by its distinctive monkey-like face. They are known for their playful and curious nature, making them excellent companions for families."
),
Pet(
  "Akita Shepherd",
  "New Jersey",
  "2.5",
  "Mating",
  Category.DOG,
  "assets/images/dog_2.jpg",
  false,
  false,
  "5 months",
  "Brown",
  "12 Kg",
  "The Akita Shepherd is a hybrid breed, a mix between the Akita and the German Shepherd. They are known for their loyalty and protective instincts, making them excellent guard dogs and family pets."
),
Pet(
  "American Foxhound",
  "Miami",
  "2.5",
  "Lost",
  Category.DOG,
  "assets/images/dog_3.jpg",
  false,
  false,
  "4.5 months",
  "White",
  "12 Kg",
  "The American Foxhound is a breed of scent hound known for its hunting abilities and stamina. They are friendly and gentle dogs, making them good companions for active families."
),
Pet(
  "Shepherd Dog",
  "Chicago",
  "2.5",
  "Lost",
  Category.DOG,
  "assets/images/dog_4.jpg",
  true,
  true,
  "4 months",
  "Brown",
  "11 Kg",
  "The Shepherd Dog is a versatile working breed known for its intelligence, loyalty, and protective instincts. They are commonly used as police and military dogs, as well as family pets."
),
Pet(
  "Australian Terrier",
  "New York",
  "2.5",
  "Adoption",
  Category.DOG,
  "assets/images/dog_5.jpg",
  true,
  false,
  "6 months",
  "White",
  "10 Kg",
  "The Australian Terrier is a small breed of dog known for its playful and affectionate nature. They are intelligent and loyal companions, making them excellent pets for families."
),
Pet(
  "Bearded Collie",
  "California",
  "2.5",
  "Adoption",
  Category.DOG,
  "assets/images/dog_6.jpg",
  false,
  false,
  "4 months",
  "Orange",
  "11 Kg",
  "The Bearded Collie is a herding breed known for its long, shaggy coat and playful personality. They are intelligent and energetic dogs, making them great companions for active families."
),
Pet(
  "Belgian Sheepdog",
  "Miami",
  "2.5",
  "Mating",
  Category.DOG,
  "assets/images/dog_7.jpg",
  true,
  false,
  "4 months",
  "Orange",
  "11 Kg",
  "The Belgian Sheepdog is a versatile working breed known for its intelligence, loyalty, and protective instincts. They are commonly used as police and military dogs, as well as family pets."
),
Pet(
  "Bloodhound",
  "California",
  "2.5",
  "Adoption",
  Category.DOG,
  "assets/images/dog_8.jpg",
  true,
  true,
  "4 months",
  "Brown",
  "11 Kg",
  "The Bloodhound is a large scent hound known for its incredible sense of smell and tracking abilities. They are gentle and affectionate dogs, making them good companions for families."
),
Pet(
  "Boston Terrier",
  "California",
  "2.5",
  "Adoption",
  Category.DOG,
  "assets/images/dog_9.jpg",
  true,
  true,
  "4 months",
  "Orange",
  "11 Kg",
  "The Boston Terrier is a small breed of dog known for its friendly and affectionate nature. They are intelligent and adaptable dogs, making them great companions for families."
),
Pet(
  "Chinese Shar-Pei",
  "New Jersey",
  "2.5",
  "Mating",
  Category.DOG,
  "assets/images/dog_10.jpg",
  false,
  false,
  "4 months",
  "Orange",
  "11 Kg",
  "The Chinese Shar-Pei is a breed of dog known for its distinctive wrinkled skin and loyal nature. They are calm and independent dogs, making them good companions for experienced owners."
),
Pet(
  "Border Collie",
  "Miami",
  "2.5",
  "Lost",
  Category.DOG,
  "assets/images/dog_11.jpg",
  false,
  false,
  "6 months",
  "Black",
  "11 Kg",
  "The Border Collie is a highly intelligent and energetic breed known for its herding abilities. They are loyal and affectionate dogs, making them great companions for active families."
),
Pet(
  "Chow Chow",
  "Chicago",
  "2.5",
  "Lost",
  Category.DOG,
  "assets/images/dog_12.jpg",
  true,
  true,
  "4 months",
  "White",
  "11 Kg",
  "The Chow Chow is a distinctive breed known for its lion-like mane and aloof demeanor. They are loyal and protective dogs, making them excellent guard dogs and family pets."
),
  ];
}
